# Generated by Django 4.1.3 on 2022-11-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sizevarient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
