# Generated by Django 4.1.3 on 2022-11-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_tshirt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('actor', models.CharField(max_length=30)),
                ('published_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Moovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('actor', models.CharField(max_length=30)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.soong')),
            ],
        ),
    ]
