# Generated by Django 4.1.3 on 2022-11-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_movie_soong_song_moovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='movie',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='slug',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Moovie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Soong',
        ),
    ]
