# Generated by Django 4.1.3 on 2022-11-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_song_movie_tshirt_slug_delete_moovie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='slug',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
