# Generated by Django 4.1.3 on 2022-11-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_payment_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size_varient',
        ),
    ]
