# Generated by Django 4.1.3 on 2022-12-11 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_order_size_varient'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='idealfor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.idealfor'),
        ),
    ]
